Add urgency to task
matthiasbeyer/task-hookrs pull request #85
Opened 2020-10-24 19:02 UTC by kdheepak

- [x] Add urgency to task
- [ ] Write tests

2020-10-24 19:12 UTC, kdheepak commented
@matthiasbeyer This is ready for your review!

2020-10-24 19:54 UTC, matthiasbeyer requested changes
Looks good apart from the stylistic stuff annotated. Please fix them, then this is ready.

2020-10-24 19:54 UTC, matthiasbeyer commented on src/task.rs
> +    pub fn set_urgency<T>(&mut self, new: Option<T>) where T: Into<Urgency> {
Please add newlines before the `where` clause to keep the style consistent.

2020-10-24 19:54 UTC, matthiasbeyer commented on src/urgency.rs
> +pub type Urgency = f64;
Please add a trailing newline.

2020-10-24 22:23 UTC, kdheepak commented on src/task.rs
> +    pub fn set_urgency<T>(&mut self, new: Option<T>) where T: Into<Urgency> {
Resolved in 06777f6.

2020-10-24 22:24 UTC, kdheepak commented on src/urgency.rs
> +pub type Urgency = f64;
All the other files don't have a trailing newline at the end of the file. Is that what you meant? Do you still want me to add it even though the other files don't have it?

2020-10-25 07:41 UTC, matthiasbeyer commented on src/urgency.rs
> +pub type Urgency = f64;
If they don't have it I'm fine this way.

2020-10-25 07:41 UTC, matthiasbeyer approved these changes

2020-10-25 14:53 UTC, kdheepak commented
Would you like me to merge this then?

2020-10-25 15:19 UTC, matthiasbeyer commented
I invited you to this repository because I think you can do these things and bring this crate forwards, so yes, feel free.
All I ask you to keep in mind is that the code for this crate does nothing unnecessarily complex or out-of-scope!

Feel free to continue working on this as you see fit. :+1:

2020-10-25 15:25 UTC, kdheepak commented
I'll definitely only make changes through PRs, so you can review them whenever you have the time!

2020-10-25 15:25 UTC, merged

2020-10-25 17:11 UTC, matthiasbeyer commented
Nice. I added a branch protection for master, so everything has to go through PR and CI must be green. That should be enough!

Thank you very much for contributing to this crate!

2020-10-25 19:28 UTC, kdheepak commented
Awesome!